//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.ZSSY.ImportSampleSourceLog {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtsampleSourceName;
		protected global::System.Web.UI.WebControls.TextBox txtsampleSourceType;
		protected global::System.Web.UI.WebControls.TextBox txtsampleSourceDescription;
		protected global::System.Web.UI.WebControls.TextBox txtpatientId;
		protected global::System.Web.UI.WebControls.TextBox txtpatientName;
		protected global::System.Web.UI.WebControls.TextBox txtpatientSex;
		protected global::System.Web.UI.WebControls.TextBox txtimportStatus;
		protected global::System.Web.UI.WebControls.TextBox txthidden;
		protected global::System.Web.UI.WebControls.TextBox txtResultStatus;
		protected global::System.Web.UI.WebControls.TextBox txtImportDate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
