//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.ZSSY.ImportSampleSourceLog {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblsampleSourceName;
	protected global::System.Web.UI.WebControls.Label lblsampleSourceType;
	protected global::System.Web.UI.WebControls.Label lblsampleSourceDescription;
	protected global::System.Web.UI.WebControls.Label lblpatientId;
	protected global::System.Web.UI.WebControls.Label lblpatientName;
	protected global::System.Web.UI.WebControls.Label lblpatientSex;
	protected global::System.Web.UI.WebControls.Label lblimportStatus;
	protected global::System.Web.UI.WebControls.Label lblhidden;
	protected global::System.Web.UI.WebControls.Label lblResultStatus;
	protected global::System.Web.UI.WebControls.Label lblImportDate;


       
    }
}
