//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportSampleSourceLog
    {
        public int id { get; set; }
        public string sampleSourceName { get; set; }
        public string sampleSourceType { get; set; }
        public string sampleSourceDescription { get; set; }
        public string patientId { get; set; }
        public string patientName { get; set; }
        public string patientSex { get; set; }
        public string importStatus { get; set; }
        public string hidden { get; set; }
        public string ResultStatus { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
    }
}
