//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTestResult
    {
        public int id { get; set; }
        public string ReportItemName { get; set; }
        public string ReportItemCode { get; set; }
        public string AbnormalIndicator { get; set; }
        public string Result { get; set; }
        public string Units { get; set; }
        public string ResultDateTime { get; set; }
        public string ReferenceResult { get; set; }
    }
}
