//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPListForSpecimen
    {
        public int Id { get; set; }
        public string PatientId { get; set; }
        public string InpNO { get; set; }
        public string VisitId { get; set; }
        public string Name { get; set; }
        public string NamePhonetic { get; set; }
        public string Sex { get; set; }
        public string DateOfBirth { get; set; }
        public string BirthPlace { get; set; }
        public string Citizenship { get; set; }
        public string Nation { get; set; }
        public string IDNO { get; set; }
        public string Identity { get; set; }
        public string ChargeType { get; set; }
        public string MailingAddress { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumberHome { get; set; }
        public string PhoneNumbeBusiness { get; set; }
        public string NextOfKin { get; set; }
        public string RelationShip { get; set; }
        public string NextOfKinAddr { get; set; }
        public string NextOfKinZipCode { get; set; }
        public string NextOfKinPhome { get; set; }
        public string DeptCode { get; set; }
        public string BedNO { get; set; }
        public string AdmissionDateTime { get; set; }
        public string DoctorInCharge { get; set; }
        public string ScheduleId { get; set; }
        public string DiagBeforeOperation { get; set; }
        public string ScheduledDateTime { get; set; }
        public string KeepSpecimenSign { get; set; }
        public string OperatingRoom { get; set; }
        public string Surgeon { get; set; }
        public string InPatPreillness { get; set; }
        public string InPatPastillness { get; set; }
        public string InPatFamillness { get; set; }
        public string LabInfo { get; set; }
    }
}
