//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.ZSSY.LabTestResult {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtReportItemName;
		protected global::System.Web.UI.WebControls.TextBox txtReportItemCode;
		protected global::System.Web.UI.WebControls.TextBox txtAbnormalIndicator;
		protected global::System.Web.UI.WebControls.TextBox txtResult;
		protected global::System.Web.UI.WebControls.TextBox txtUnits;
		protected global::System.Web.UI.WebControls.TextBox txtResultDateTime;
		protected global::System.Web.UI.WebControls.TextBox txtReferenceResult;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
