//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.ZSSY.LabTestResult {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblReportItemName;
	protected global::System.Web.UI.WebControls.Label lblReportItemCode;
	protected global::System.Web.UI.WebControls.Label lblAbnormalIndicator;
	protected global::System.Web.UI.WebControls.Label lblResult;
	protected global::System.Web.UI.WebControls.Label lblUnits;
	protected global::System.Web.UI.WebControls.Label lblResultDateTime;
	protected global::System.Web.UI.WebControls.Label lblReferenceResult;


       
    }
}
