//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.OPListForSpecimen {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtPatientId;
		protected global::System.Web.UI.WebControls.TextBox txtInpNO;
		protected global::System.Web.UI.WebControls.TextBox txtVisitId;
		protected global::System.Web.UI.WebControls.TextBox txtName;
		protected global::System.Web.UI.WebControls.TextBox txtNamePhonetic;
		protected global::System.Web.UI.WebControls.TextBox txtSex;
		protected global::System.Web.UI.WebControls.TextBox txtDateOfBirth;
		protected global::System.Web.UI.WebControls.TextBox txtBirthPlace;
		protected global::System.Web.UI.WebControls.TextBox txtCitizenship;
		protected global::System.Web.UI.WebControls.TextBox txtNation;
		protected global::System.Web.UI.WebControls.TextBox txtIDNO;
		protected global::System.Web.UI.WebControls.TextBox txtIdentity;
		protected global::System.Web.UI.WebControls.TextBox txtChargeType;
		protected global::System.Web.UI.WebControls.TextBox txtMailingAddress;
		protected global::System.Web.UI.WebControls.TextBox txtZipCode;
		protected global::System.Web.UI.WebControls.TextBox txtPhoneNumberHome;
		protected global::System.Web.UI.WebControls.TextBox txtPhoneNumbeBusiness;
		protected global::System.Web.UI.WebControls.TextBox txtNextOfKin;
		protected global::System.Web.UI.WebControls.TextBox txtRelationShip;
		protected global::System.Web.UI.WebControls.TextBox txtNextOfKinAddr;
		protected global::System.Web.UI.WebControls.TextBox txtNextOfKinZipCode;
		protected global::System.Web.UI.WebControls.TextBox txtNextOfKinPhome;
		protected global::System.Web.UI.WebControls.TextBox txtDeptCode;
		protected global::System.Web.UI.WebControls.TextBox txtBedNO;
		protected global::System.Web.UI.WebControls.TextBox txtAdmissionDateTime;
		protected global::System.Web.UI.WebControls.TextBox txtDoctorInCharge;
		protected global::System.Web.UI.WebControls.TextBox txtScheduleId;
		protected global::System.Web.UI.WebControls.TextBox txtDiagBeforeOperation;
		protected global::System.Web.UI.WebControls.TextBox txtScheduledDateTime;
		protected global::System.Web.UI.WebControls.TextBox txtKeepSpecimenSign;
		protected global::System.Web.UI.WebControls.TextBox txtOperatingRoom;
		protected global::System.Web.UI.WebControls.TextBox txtSurgeon;
		protected global::System.Web.UI.WebControls.TextBox txtInPatPreillness;
		protected global::System.Web.UI.WebControls.TextBox txtInPatPastillness;
		protected global::System.Web.UI.WebControls.TextBox txtInPatFamillness;
		protected global::System.Web.UI.WebControls.TextBox txtLabInfo;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
