//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.OPListForSpecimen {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblPatientId;
	protected global::System.Web.UI.WebControls.Label lblInpNO;
	protected global::System.Web.UI.WebControls.Label lblVisitId;
	protected global::System.Web.UI.WebControls.Label lblName;
	protected global::System.Web.UI.WebControls.Label lblNamePhonetic;
	protected global::System.Web.UI.WebControls.Label lblSex;
	protected global::System.Web.UI.WebControls.Label lblDateOfBirth;
	protected global::System.Web.UI.WebControls.Label lblBirthPlace;
	protected global::System.Web.UI.WebControls.Label lblCitizenship;
	protected global::System.Web.UI.WebControls.Label lblNation;
	protected global::System.Web.UI.WebControls.Label lblIDNO;
	protected global::System.Web.UI.WebControls.Label lblIdentity;
	protected global::System.Web.UI.WebControls.Label lblChargeType;
	protected global::System.Web.UI.WebControls.Label lblMailingAddress;
	protected global::System.Web.UI.WebControls.Label lblZipCode;
	protected global::System.Web.UI.WebControls.Label lblPhoneNumberHome;
	protected global::System.Web.UI.WebControls.Label lblPhoneNumbeBusiness;
	protected global::System.Web.UI.WebControls.Label lblNextOfKin;
	protected global::System.Web.UI.WebControls.Label lblRelationShip;
	protected global::System.Web.UI.WebControls.Label lblNextOfKinAddr;
	protected global::System.Web.UI.WebControls.Label lblNextOfKinZipCode;
	protected global::System.Web.UI.WebControls.Label lblNextOfKinPhome;
	protected global::System.Web.UI.WebControls.Label lblDeptCode;
	protected global::System.Web.UI.WebControls.Label lblBedNO;
	protected global::System.Web.UI.WebControls.Label lblAdmissionDateTime;
	protected global::System.Web.UI.WebControls.Label lblDoctorInCharge;
	protected global::System.Web.UI.WebControls.Label lblScheduleId;
	protected global::System.Web.UI.WebControls.Label lblDiagBeforeOperation;
	protected global::System.Web.UI.WebControls.Label lblScheduledDateTime;
	protected global::System.Web.UI.WebControls.Label lblKeepSpecimenSign;
	protected global::System.Web.UI.WebControls.Label lblOperatingRoom;
	protected global::System.Web.UI.WebControls.Label lblSurgeon;
	protected global::System.Web.UI.WebControls.Label lblInPatPreillness;
	protected global::System.Web.UI.WebControls.Label lblInPatPastillness;
	protected global::System.Web.UI.WebControls.Label lblInPatFamillness;
	protected global::System.Web.UI.WebControls.Label lblLabInfo;


       
    }
}
