//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.ZSSY.LabTestMaster {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtId;
		protected global::System.Web.UI.WebControls.TextBox txtTestNo;
		protected global::System.Web.UI.WebControls.TextBox txtpriorityIndicator;
		protected global::System.Web.UI.WebControls.TextBox txtWorkingId;
		protected global::System.Web.UI.WebControls.TextBox txtTestCause;
		protected global::System.Web.UI.WebControls.TextBox txtRelevantClinicDiag;
		protected global::System.Web.UI.WebControls.TextBox txtSpecimen;
		protected global::System.Web.UI.WebControls.TextBox txtSpcmReceivedDateTime;
		protected global::System.Web.UI.WebControls.TextBox txtOrderingDept;
		protected global::System.Web.UI.WebControls.TextBox txtorderingProvider;
		protected global::System.Web.UI.WebControls.TextBox txtPerformedBy;
		protected global::System.Web.UI.WebControls.TextBox txtResultStatus;
		protected global::System.Web.UI.WebControls.TextBox txtResultsRptDateTime;
		protected global::System.Web.UI.WebControls.TextBox txttranscriptionist;
		protected global::System.Web.UI.WebControls.TextBox txtVerifiedBy;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
