//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.ZSSY.LabTestMaster {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblTestNo;
	protected global::System.Web.UI.WebControls.Label lblpriorityIndicator;
	protected global::System.Web.UI.WebControls.Label lblWorkingId;
	protected global::System.Web.UI.WebControls.Label lblTestCause;
	protected global::System.Web.UI.WebControls.Label lblRelevantClinicDiag;
	protected global::System.Web.UI.WebControls.Label lblSpecimen;
	protected global::System.Web.UI.WebControls.Label lblSpcmReceivedDateTime;
	protected global::System.Web.UI.WebControls.Label lblOrderingDept;
	protected global::System.Web.UI.WebControls.Label lblorderingProvider;
	protected global::System.Web.UI.WebControls.Label lblPerformedBy;
	protected global::System.Web.UI.WebControls.Label lblResultStatus;
	protected global::System.Web.UI.WebControls.Label lblResultsRptDateTime;
	protected global::System.Web.UI.WebControls.Label lbltranscriptionist;
	protected global::System.Web.UI.WebControls.Label lblVerifiedBy;


       
    }
}
