//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码,则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditRec
    {
        public string id { get; set; }
        public  string  obj_id { get; set; }
        public string obj_name { get; set; }
        public string user_name { get; set; }
        public string created_at { get; set; }
        public string created_time { get; set; }
        public string message { get; set; }
        public string comments { get; set; }
    }
}
